# PREPARE
# ----------------------------------------------------
FROM localhost/minus-one-base:latest

COPY grimoire/build.sh /build_scripts/grimoire.sh
COPY grimoire/90-minus-one-machine.conf \
    /usr/lib/dracut/dracut.conf.d/90-minus-one-machine.conf

# ASSEMBLE
# ----------------------------------------------------
ARG MINUS_ONE_BUILD_ID
RUN --mount=type=tmpfs,dst=/var \
    --mount=type=tmpfs,dst=/tmp \
    --mount=type=tmpfs,dst=/boot \
    --mount=type=secret,id=bluetooth \
    test -n "$MINUS_ONE_BUILD_ID" && \
    bash /build_scripts/grimoire.sh
RUN rm -rf /build_scripts

# COMMIT
# ----------------------------------------------------
RUN ostree container commit
RUN bootc container lint
